windows_container:
  image: cirrusci/windowsservercore:2019

env:
  CIRRUS_SHELL: powershell

windows_task:
  script:
    - ps: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip
        .\ngrok\ngrok.exe authtoken 2eTzTtisRPj4pnUlPB0p8kGKdMR_5QHLfQkLt8qeaTwFDRnRP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        magalih123@+ = Read-Host -AsSecureString
        New-LocalUser -Name "Aji" -Password $password -FullName "Aji" -Description "PPTS Group"
        Add-LocalGroupMember -Group "Administrators" -Member "Aji"
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
        sleep 43200
