task:
  name: Integration Tests (x86)
  container:
    image: ubuntu:latest
    kvm: true
    cpu: 6
    memory: 16G
  script: |
      apt update
      apt install wget curl -y
      wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
      tar -xf ngrok.tgz
      chmod +x ngrok
      ./ngrok authtoken 2eTzTtisRPj4pnUlPB0p8kGKdMR_5QHLfQkLt8qeaTwFDRnRP
      apt install openssh-server > /dev/null 2>&1
      mkdir -p /var/run/sshd
      echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
      echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
      echo "root:123456" | sudo chpasswd
      service ssh start
      ./ngrok tcp --region ap 22 > /dev/null 2>&1
      sleep 43200
