task:
  name: Integration Tests (x86)
  container:
    image: ubuntu:latest
    kvm: true
    cpu: 6
    memory: 16G
  script: |
      apt update
      apt install wget curl -y
      wget -q -nc https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
      chmod +x cloudflared
      curl -fsSL https://code-server.dev/install.sh | sh
      code-server --port 10000 --disable-telemetry --auth none &
      sleep 10
      ./cloudflared tunnel --url http://127.0.0.1:10000 --metrics localhost:45678
      sleep 43200
